### PR TITLE
fix: add javascript patterns examples files

### PR DESCRIPTION
**Pull request by bruuuuuuuce**
adds `patterns.ts` example file to be consumed downstream in dev docs

### CODE REVIEW

**Comment by malandis** [comment]
There are various warnings reported by GH actions, eg unused imports and non-null assertions. Were these intended?

**Comment by bruuuuuuuce** [comment]
> There are various warnings reported by GH actions, eg unused imports and non-null assertions. Were these intended?

hmmm no, the non-null assertion is expected, i can probably ignore that with a lint rule. The unused imports should be removed good catch

**Comment by malandis** [comment]
> hmmm no, the non-null assertion is expected, i can probably ignore that with a lint rule. The unused imports should be removed good catch

Thanks. Those appear in GH actions in every subsequent PR involving those files if left unaddressed.

**Review by malandis — APPROVED** [review]
🏆

**Pull request merged**
